In [2]:
from PIL import Image
import PIL.ImageOps
import numpy as np
import sys
import os
import csv

fileList = []

#Useful function to create list of all JPG files in dir
def createFileList(myDir, format='.jpg'):
    #fileList = []
    print(myDir)
    print(fileList)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('dataset_sample')
print(fileList)

for file in fileList:
    print(file)
    img_file = Image.open(file)
    #img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()
    img_grey = PIL.ImageOps.invert(img_grey)
    # Save values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    #value[value<128] = 1 #black
    #value[value>=128] = 0 #white
    
    #value[value<128] = 255 #black
    #value[value>=128] = 0 #white
    
    print(value)
    
    #manual
    #char = input("Choose Character: ")
    #value = np.insert(value, 0, char)
    #print(value)
    #auto
    #print(os.path.basename(file))
    fileName = os.path.basename(file)
    fileName = os.path.splitext(fileName)[0]
    #remove last 3 chars from string - these are variation nums
    #char = fileName[:-3]
    char = fileName[:-1]
    
    #print(os.path.split(file)[-1])
    print(char)
    
    #flatten into 1D
    value = value.flatten()
    print(value)
    
    #save
    with open("img_pixels.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)
        
    with open("img_labels.txt", 'a') as f:
        f.write(char+"\n")
        #\n writes on new line
        

dataset_sample
[]
['dataset_sample/b/b_29871.jpg', 'dataset_sample/b/exp89337.jpg', 'dataset_sample/b/exp30526.jpg', 'dataset_sample/b/b_50774.jpg', 'dataset_sample/b/b_34339.jpg', 'dataset_sample/b/exp7364.jpg', 'dataset_sample/b/exp49176.jpg', 'dataset_sample/b/exp45018.jpg', 'dataset_sample/b/exp29603.jpg', 'dataset_sample/b/exp43836.jpg', 'dataset_sample/b/exp3583.jpg', 'dataset_sample/b/exp38501.jpg', 'dataset_sample/b/exp15141.jpg', 'dataset_sample/b/exp30505.jpg', 'dataset_sample/b/exp14987.jpg', 'dataset_sample/b/exp99928.jpg', 'dataset_sample/b/b_105498.jpg', 'dataset_sample/b/exp18843.jpg', 'dataset_sample/b/exp32315.jpg', 'dataset_sample/b/b_76687.jpg', 'dataset_sample/b/b_29280.jpg', 'dataset_sample/b/exp65119.jpg', 'dataset_sample/b/exp32515.jpg', 'dataset_sample/b/b_113633.jpg', 'dataset_sample/b/exp8302.jpg', 'dataset_sample/b/exp33558.jpg', 'dataset_sample/b/exp26637.jpg', 'dataset_sample/b/exp29920.jpg', 'dataset_sample/b/exp13646.jpg', 'dataset_sample/b/exp37890.jpg',

dataset_sample/b/b_112643.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
b_11264
[0 0 0 ... 0 0 0]
dataset_sample/b/exp17554.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp1755
[0 0 0 ... 0 0 0]
dataset_sample/b/b_33527.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [3 0 0 ... 0 0 0]]
b_3352
[0 0 0 ... 0 0 0]
dataset_sample/b/b_38240.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
b_3824
[0 0 0 ... 0 0 0]
dataset_sample/b/b_80125.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
b_8012
[0 0 0 ... 0 0 0]
dataset_sample/b/exp31647.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0

dataset_sample/4/exp3793.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp379
[0 0 0 ... 0 0 0]
dataset_sample/4/exp95053.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp9505
[0 0 0 ... 0 0 0]
dataset_sample/4/exp38828.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp3882
[0 0 0 ... 0 0 0]
dataset_sample/4/exp7223.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp722
[0 0 0 ... 0 0 0]
dataset_sample/4/exp22186.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp2218
[0 0 0 ... 0 0 0]
dataset_sample/4/4_34937.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 

dataset_sample/7/exp46542.jpg
[[1 0 1 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [2 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp4654
[1 0 1 ... 0 0 0]
dataset_sample/7/exp18469.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp1846
[0 0 0 ... 0 0 0]
dataset_sample/7/7_17583.jpg
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [2 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
7_1758
[1 0 0 ... 0 0 0]
dataset_sample/7/exp93874.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp9387
[0 0 0 ... 0 0 0]
dataset_sample/7/exp56330.jpg
[[1 0 1 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [2 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp5633
[1 0 1 ... 0 0 0]
dataset_sample/7/exp25331.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ...

[0 0 0 ... 0 0 0]
dataset_sample/0/0_59091.jpg
[[1 0 1 ... 0 0 0]
 [0 5 0 ... 0 0 0]
 [2 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0_5909
[1 0 1 ... 0 0 0]
dataset_sample/0/0_48038.jpg
[[1 0 0 ... 0 0 0]
 [2 0 2 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0_4803
[1 0 0 ... 0 0 0]
dataset_sample/0/exp87959.jpg
[[1 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp8795
[1 0 0 ... 0 0 0]
dataset_sample/0/exp41418.jpg
[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 2 4]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp4141
[0 0 0 ... 0 0 0]
dataset_sample/0/0_63404.jpg
[[0 0 0 ... 0 2 1]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 3]
 ...
 [2 0 0 ... 0 0 0]
 [0 2 2 ... 0 0 0]
 [0 2 0 ... 0 0 0]]
0_6340
[0 0 0 ... 0 0 0]
dataset_sample/0/exp44814.jpg
[[1 0 1 ... 2 0 0]
 [0 5 0 ... 0 0 4]
 [2 0 1 ... 3 2 0]
 ...
 [0 0 0 ... 0 0 

dataset_sample/0/exp13909.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp1390
[0 0 0 ... 0 0 0]
dataset_sample/0/0_31093.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 0 ... 0 0 0]
 [3 0 2 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0_3109
[0 0 0 ... 0 0 0]
dataset_sample/0/exp93334.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp9333
[0 0 0 ... 0 0 0]
dataset_sample/0/exp55278.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]]
exp5527
[0 0 0 ... 0 0 0]
dataset_sample/0/0_26709.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0_2670
[0 0 0 ... 0 0 0]
dataset_sample/0/0_61875.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 

dataset_sample/9/exp65005.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp6500
[0 0 0 ... 0 0 0]
dataset_sample/9/exp24318.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp2431
[0 0 0 ... 0 0 0]
dataset_sample/9/exp48598.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp4859
[0 0 0 ... 0 0 0]
dataset_sample/9/exp67492.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp6749
[0 0 0 ... 0 0 0]
dataset_sample/9/exp35105.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp3510
[0 0 0 ... 0 0 0]
dataset_sample/9/exp89752.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 .