In [17]:
from PIL import Image
import PIL.ImageOps
import numpy as np
import sys
import os
import csv

fileList = []

#Useful function to create list of all JPG files in dir
def createFileList(myDir, format='.jpg'):
    #fileList = []
    print(myDir)
    print(fileList)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('dataset_sample')
print(fileList)

for file in fileList:
    print(file)
    img_file = Image.open(file)
    #img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()
    img_grey = PIL.ImageOps.invert(img_grey)
    # Save values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    #value[value<128] = 1 #black
    #value[value>=128] = 0 #white
    
    #value[value<128] = 255 #black
    #value[value>=128] = 0 #white
    
    print(value)
    
    #manual
    #char = input("Choose Character: ")
    #value = np.insert(value, 0, char)
    #print(value)
    #auto
    #print(os.path.basename(file))
    fileName = os.path.basename(file)
    fileName = os.path.splitext(fileName)[0]
    #remove last 3 chars from string - these are variation nums
    #char = fileName[:-3]
    char = fileName[:-1]
    
    #print(os.path.split(file)[-1])
    print(char)
    
    #flatten into 1D
    value = value.flatten()
    print(value)
    
    #save
    with open("img_pixels.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)
        
    with open("img_labels.txt", 'a') as f:
        f.write(char+"\n")
        #\n writes on new line
        

dataset_sample
[]
['dataset_sample/7/exp35423.jpg', 'dataset_sample/7/exp1906.jpg', 'dataset_sample/7/7_55472.jpg', 'dataset_sample/7/exp14480.jpg', 'dataset_sample/7/7_99833.jpg', 'dataset_sample/7/exp38452.jpg', 'dataset_sample/7/exp58389.jpg', 'dataset_sample/7/exp37651.jpg', 'dataset_sample/7/exp1063.jpg', 'dataset_sample/7/exp2159.jpg', 'dataset_sample/7/exp48506.jpg', 'dataset_sample/7/exp187.jpg', 'dataset_sample/7/exp92248.jpg', 'dataset_sample/7/exp65730.jpg', 'dataset_sample/7/exp59826.jpg', 'dataset_sample/7/exp43222.jpg', 'dataset_sample/7/exp58485.jpg', 'dataset_sample/7/exp25534.jpg', 'dataset_sample/7/exp54029.jpg', 'dataset_sample/7/exp27227.jpg', 'dataset_sample/7/7_38282.jpg', 'dataset_sample/7/7_41069.jpg', 'dataset_sample/7/exp50999.jpg', 'dataset_sample/7/exp78138.jpg', 'dataset_sample/7/exp42733.jpg', 'dataset_sample/7/7_277.jpg', 'dataset_sample/7/exp58802.jpg', 'dataset_sample/7/exp17530.jpg', 'dataset_sample/7/exp78971.jpg', 'dataset_sample/7/exp34419.jpg', 'da

dataset_sample/7/7_57605.jpg
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
7_5760
[0 0 0 ... 0 0 0]
dataset_sample/7/exp59526.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp5952
[0 0 0 ... 0 0 0]
dataset_sample/7/exp16700.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp1670
[0 0 0 ... 0 0 0]
dataset_sample/7/exp44839.jpg
[[  0   1   0 ...   0   0   0]
 [  1   0 255 ...   0   0   0]
 [  0   2 252 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
exp4483
[0 1 0 ... 0 0 0]
dataset_sample/7/exp44155.jpg
[[0 2 0 ... 0 0 0]
 [3 0 1 ... 0 0 0]
 [0 3 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp4

dataset_sample/0/exp49899.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp4989
[0 0 0 ... 0 0 0]
dataset_sample/0/exp83575.jpg
[[1 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [4 0 0 ... 0 0 0]
 ...
 [0 1 2 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 4 0 ... 0 0 0]]
exp8357
[1 1 0 ... 0 0 0]
dataset_sample/0/0_65547.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0_6554
[0 0 0 ... 0 0 0]
dataset_sample/0/0_63410.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [3 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 5 0 ... 0 0 0]]
0_6341
[0 0 0 ... 0 0 0]
dataset_sample/0/exp62445.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
exp6244
[0 0 0 ... 0 0 0]
dataset_sample/0/exp36480.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0