In [31]:
from PIL import Image
import numpy as np
import sys
import os
import csv

fileList = []

#Useful function to create list of all JPG files in dir
def createFileList(myDir, format='.jpg'):
    #fileList = []
    print(myDir)
    print(fileList)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('dataset_minimised')
print(fileList)

for file in fileList:
    print(file)
    img_file = Image.open(file)
    #img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image black and white
    img_grey = img_file.convert('1')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value[value<128] = 1 #black
    value[value>=128] = 0 #white
    
    print(value)
    
    #manual
    #char = input("Choose Character: ")
    #value = np.insert(value, 0, char)
    #print(value)
    #auto
    #print(os.path.basename(file))
    fileName = os.path.basename(file)
    fileName = os.path.splitext(fileName)[0]
    #remove last 3 chars from string - these are variation nums
    char = fileName[:-3]
    
    #print(os.path.split(file)[-1])
    print(char)
    
    #flatten into 1D
    value = value.flatten()
    print(value)
    
    #save
    with open("img_pixels.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)
        
    with open("img_labels.txt", 'a') as f:
        f.write(char+"\n")
        #\n writes on new line
        

dataset_minimised
[]
['dataset_minimised/-000.jpg', 'dataset_minimised/=000.jpg', 'dataset_minimised/slash000.jpg']
dataset_minimised/-000.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
-
[0 0 0 ... 0 0 0]
dataset_minimised/=000.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
=
[0 0 0 ... 0 0 0]
dataset_minimised/slash000.jpg
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
slash
[0 0 0 ... 0 0 0]
